IF EXISTS (
SELECT *
    FROM INFORMATION_SCHEMA.ROUTINES
WHERE SPECIFIC_SCHEMA = N'dbo'
    AND SPECIFIC_NAME = N'GetStudents'
    AND ROUTINE_TYPE = N'PROCEDURE'
)
DROP PROCEDURE dbo.GetStudents
GO
CREATE PROCEDURE dbo.GetStudents
AS
BEGIN
    SELECT * FROM Students;
END
GO