IF EXISTS (
SELECT *
    FROM INFORMATION_SCHEMA.ROUTINES
WHERE SPECIFIC_SCHEMA = N'dbo'
    AND SPECIFIC_NAME = N'GetTutorials'
    AND ROUTINE_TYPE = N'PROCEDURE'
)
DROP PROCEDURE dbo.GetTutorials
GO
CREATE PROCEDURE dbo.GetTutorials
AS
BEGIN
    SELECT * FROM Tutorial;
END
GO