SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (
SELECT *
    FROM INFORMATION_SCHEMA.ROUTINES
WHERE SPECIFIC_SCHEMA = N'dbo'
    AND SPECIFIC_NAME = N'GetTutorialById'
    AND ROUTINE_TYPE = N'PROCEDURE'
)
DROP PROCEDURE dbo.GetTutorialById
GO

CREATE PROCEDURE [dbo].[GetTutorialById]
    @id int = 0
AS
BEGIN
    SELECT * FROM Tutorial where Id = @id
END

GO
