USE DB_REFODY
GO
DECLARE @TIPO INT
SET @TIPO	 =	(SELECT IdtipoE FROM TblTipoEstado WHERE Tipo = 'TUTORIA')
EXECUTE SP_ESTADO_INSERT 'RESERVADA', @TIPO
EXECUTE SP_ESTADO_INSERT 'CANCELADA', @TIPO
EXECUTE SP_ESTADO_INSERT 'COMPLETADA', @TIPO


SET @TIPO	 =	(SELECT IdtipoE FROM TblTipoEstado WHERE Tipo = 'TEMA')
EXECUTE SP_ESTADO_INSERT 'ESTUDIANDO', @TIPO
EXECUTE SP_ESTADO_INSERT 'DOMINIO FULL', @TIPO
EXECUTE SP_ESTADO_INSERT 'DOMINIO INTERMEDIO', @TIPO
GO
CREATE TRIGGER TG_ESTADO_UPDATE
	ON TBLESTADO
	FOR UPDATE
	AS
		RAISERROR ('NO PUEDE ALTERAR LA EL REGISTRO',10,1)
		ROLLBACK TRANSACTION

GO
CREATE TRIGGER TG_ESTADO_DELETE
	ON TBLESTADO
	FOR DELETE
	AS
		RAISERROR ('NO PUEDE ALTERAR LA EL REGISTRO',10,1)
		ROLLBACK TRANSACTION
GO
CREATE TRIGGER TG_TIPOESTADO_UPDATE
	ON TBLTIPOESTADO
	FOR UPDATE
	AS
		RAISERROR ('NO PUEDE ALTERAR LA EL REGISTRO',10,1)
		ROLLBACK TRANSACTION

GO
CREATE TRIGGER TG_TIPOESTADO_DELETE
	ON TBLTIPOESTADO
	FOR DELETE
	AS
		RAISERROR ('NO PUEDE ALTERAR LA EL REGISTRO',10,1)
		ROLLBACK TRANSACTION


GO
CREATE TRIGGER TG_TUTORIA_UPDATE
	ON TBLTUTORIA 
	FOR UPDATE
	AS
	BEGIN
		DECLARE @ESTADO VARCHAR(20) 
		SELECT @ESTADO = E.Estado FROM deleted AS I 
			INNER JOIN TblEstado AS E ON I.IdEstado = E.IdEstado
		IF(@ESTADO IN ('COMPLETADA' , 'CANCELADA'))
			BEGIN
				RAISERROR ('NO PUEDE ALTERAR LA EL REGISTRO',10,1)
				ROLLBACK TRANSACTION
			END
		ELSE IF ( UPDATE(RESEÑA) OR UPDATE(CALIFICACION))
			BEGIN
			IF((SELECT Fecha FROM deleted) < GETDATE())
				BEGIN
					RAISERROR ('NO PUEDE AGREGAR LA RESEÑA ANTES DE LA TUTORIA',11,1)
					ROLLBACK TRANSACTION
				END
			END
	END

GO
CREATE PROCEDURE SP_TUTORIA_UPDATE_FECHA
	@ID			INT
	,@FECHA	DATETIME
	,@DURACION INT
AS
BEGIN
	UPDATE Tbltutoria
	SET
		Duracion = @DURACION
		,Fecha	 = @FECHA
	WHERE
		IdTutoria =	@ID
	
END

GO
CREATE PROCEDURE SP_TUTORIA_COMPLETAR 
	@ID	INT  
	AS
BEGIN
	UPDATE Tbltutoria
	SET
		IdEstado = (SELECT IdEstado FROM TblEstado WHERE Estado = 'COMPLETADA')
	WHERE
		IdTutoria =	@ID
END

GO
CREATE PROCEDURE SP_TUTORIA_CANCELAR 
	@ID	INT  
	AS
BEGIN
	UPDATE Tbltutoria
	SET
		IdEstado = (SELECT IdEstado FROM TblEstado WHERE Estado = 'CANCELADA')
	WHERE
		IdTutoria =	@ID
END



GO
CREATE PROCEDURE SP_TUTORIA_UPDATE_RESEÑA
	@ID			INT
	,@CAL		TINYINT
	,@RESEÑA VARCHAR(500)
AS
BEGIN
	UPDATE Tbltutoria
	SET
		Calificacion = @CAL
		,Reseña	 = @RESEÑA
	WHERE
		IdTutoria =	@ID
	
END