---ESTADOS
USE TutorialsDB
GO

EXECUTE SP_TIPOE_INSERT 'TUTORIA'
EXECUTE SP_TIPOE_INSERT 'TEMA'

GO
EXECUTE SP_DIA_INSERT 'LUNES'
EXECUTE SP_DIA_INSERT 'MARTES'
EXECUTE SP_DIA_INSERT 'MIERCOLES'
EXECUTE SP_DIA_INSERT 'JUEVES'
EXECUTE SP_DIA_INSERT 'VIERNES'
EXECUTE SP_DIA_INSERT 'SABADO'
EXECUTE SP_DIA_INSERT 'DOMINGO'

GO
EXECUTE SP_TIPOU_INSERT 'TUTOR'
EXECUTE SP_TIPOU_INSERT 'CLIENTE'

GO
EXECUTE SP_TIPOD_INSERT 'CEDULA'
EXECUTE SP_TIPOD_INSERT 'PASAPORTE'
EXECUTE SP_TIPOD_INSERT 'ACTA NACIMIENTO'

GO
CREATE PROCEDURE SP_TUTOR_INSERT 
		@IdTipoD		INT
		,@DocumentoId	BIGINT
		,@idSector		INT
		,@Calle		VARCHAR(100)
AS
BEGIN
	INSERT INTO TblTutor (IdTipoD,IdSector,NumeroDoc,Calle)
		VALUES(@IdTipoD, @idSector, @DocumentoId, @Calle)
	
END	
GO

CREATE PROCEDURE SP_TUTORHORARIO_INSERT
	@idTutor	INT
	,@Dia		INT
AS
	INSERT INTO	TblTutorHorario (IdTutor,Dia)	VALUES(@idTutor,@Dia)

GO

CREATE PROCEDURE SP_HORARIOHORA_INSERT
		@IdTH		INT
		,@Inicio	TIME
		,@Fin		TIME
AS
BEGIN 
		IF(@Inicio > @Fin)
			BEGIN
				PRINT('LA FECHA DE INICIO TIENE QUE SER ANTES DE EMPEZAR')
			END
		ELSE
			BEGIN
				INSERT INTO TblHorarioHora(IdTH,inicio,fin) VALUES(@IdTH,@Inicio,@Fin)
			END
END

GO
CREATE PROCEDURE SP_TUTORIA_INSERT
	@idTT		INT
	,@USER		INT
	,@idEstado	INT
	,@Precio	DECIMAL(6,2)
	,@FECHA		DATE
	,@Duracion	INT
AS
BEGIN 
	DECLARE @TABLA	VARCHAR(20)
	SET @TABLA = (SELECT T.Tipo FROM TblEstado AS E
					INNER JOIN TblTipoE AS T ON E.IdTipoE = T.idtipoE
					WHERE E.IdEstado = @IdEstado)
	IF(@TABLA = 'TUTORIA')
		BEGIN
			INSERT INTO TblTutoria( IdTT,,IdUsuario, IdEstado,Fecha,Duracion,Precio)
				VALUES(@IdTT,@USER,@IdEstado,@FECHA,@Duracion,@Precio)
		END
	ELSE
		BEGIN 
			PRINT('EL ESTADO NO PERTENECE  A ESTA TABLA')
		END
END

GO
CREATE PROCEDURE SP_TUTORTEMA_INSERT
	@idTema		INT
	,@idEstado	INT
	,@Precio	DECIMAL(6,2)
AS
BEGIN 
	DECLARE @TABLA	VARCHAR(20)
	SET @TABLA = (SELECT T.Tipo FROM TblEstado AS E
					INNER JOIN TblTipoE AS T ON E.IdTipoE = T.idtipoE
					WHERE E.IdEstado = @IdEstado)
	IF(@TABLA = 'TEMA')
		BEGIN
			INSERT INTO TblTutorTema( IdTema,IdEstado,Precio)
				VALUES(@IdTema,@IdEstado,@Precio)
		END
	ELSE
		BEGIN 
			PRINT('EL ESTADO NO PERTENECE  A ESTA TABLA')
		END
END

GO
CREATE PROCEDURE SP_TUTORIA_DETALLE_INSERT 
	@IdTutoria	INT
	,@IdSubTema	INT
AS
BEGIN 
	DECLARE @TEMA	INT
	SET @TEMA = (SELECT TT.IdTema FROM TblTutoria AS T
					INNER JOIN TBLTUTORTEMA AS TT ON T.IdTT = TT.IdTT
					WHERE @IdTutoria = T.IdTutoria)
	IF (@TEMA = (SELECT IdTema FROM TblSubTema WHERE IdSubTema = @IdSubTema))
		BEGIN
			INSERT INTO TblTutoriaDetalle(IdTutoria,idSubTema) 
				VALUES (@IdTutoria,@IdSubTema)
		END
	ELSE
		BEGIN 
			PRINT ('EL SUBTEMA ES DEL TEMA ELEGIDO EN LA TUTORIA')
		END
END
